# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\x12\x0breplication\"#\n\x0fGetTopicRequest\x12\x10\n\x08topic_id\x18\x01 \x01(\t\"W\n\x10GetTopicResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\x05topic\x18\x03 \x01(\x0b\x32\x12.replication.Topic\"#\n\x0fGetQueueRequest\x12\x10\n\x08queue_id\x18\x01 \x01(\t\"W\n\x10GetQueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\x05queue\x18\x03 \x01(\x0b\x32\x12.replication.Queue\">\n\x0f\x46\x61ilOverRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x0f\n\x07isTopic\x18\x02 \x01(\x08\x12\n\n\x02id\x18\x03 \x01(\t\"4\n\x10\x46\x61ilOverResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"P\n\x05Topic\x12\x10\n\x08topic_id\x18\x01 \x01(\t\x12\r\n\x05\x61utor\x18\x02 \x01(\t\x12&\n\x08messages\x18\x03 \x03(\x0b\x32\x14.replication.Message\"P\n\x05Queue\x12\x10\n\x08queue_id\x18\x01 \x01(\t\x12\r\n\x05\x61utor\x18\x02 \x01(\t\x12&\n\x08messages\x18\x03 \x03(\x0b\x32\x14.replication.Message\"a\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x0e\n\x06parent\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t2\xef\x01\n\x12ReplicationService\x12G\n\x08GetTopic\x12\x1c.replication.GetTopicRequest\x1a\x1d.replication.GetTopicResponse\x12G\n\x08GetQueue\x12\x1c.replication.GetQueueRequest\x1a\x1d.replication.GetQueueResponse\x12G\n\x08\x46\x61ilOver\x12\x1c.replication.FailOverRequest\x1a\x1d.replication.FailOverResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTOPICREQUEST']._serialized_start=34
  _globals['_GETTOPICREQUEST']._serialized_end=69
  _globals['_GETTOPICRESPONSE']._serialized_start=71
  _globals['_GETTOPICRESPONSE']._serialized_end=158
  _globals['_GETQUEUEREQUEST']._serialized_start=160
  _globals['_GETQUEUEREQUEST']._serialized_end=195
  _globals['_GETQUEUERESPONSE']._serialized_start=197
  _globals['_GETQUEUERESPONSE']._serialized_end=284
  _globals['_FAILOVERREQUEST']._serialized_start=286
  _globals['_FAILOVERREQUEST']._serialized_end=348
  _globals['_FAILOVERRESPONSE']._serialized_start=350
  _globals['_FAILOVERRESPONSE']._serialized_end=402
  _globals['_TOPIC']._serialized_start=404
  _globals['_TOPIC']._serialized_end=484
  _globals['_QUEUE']._serialized_start=486
  _globals['_QUEUE']._serialized_end=566
  _globals['_MESSAGE']._serialized_start=568
  _globals['_MESSAGE']._serialized_end=665
  _globals['_REPLICATIONSERVICE']._serialized_start=668
  _globals['_REPLICATIONSERVICE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
